version: '3.9'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    command: python /usr/src/app/manage.py runserver 0.0.0.0:8000

    volumes :
      - .:/usr/src/app
    
    depends_on:
      - db

  
  db:
    image: postgres:13

    volumes:
     - postgre_data:/var/lib/postgresql/data/
    environment :
     - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgre_data:



    